# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# Azure DevOps Pipeline for .NET Core with Fixed Missing Tools Installation

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    echo "Installing missing tools..."
    sudo apt update
    sudo apt install -y apt-transport-https ca-certificates gnupg software-properties-common
    sudo apt install -y nuget
    wget -qO- https://aka.ms/InstallAzureCLIDeb | sudo bash
  displayName: 'Install Missing Tools (NuGet, Azure CLI)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build .NET Core Project'
